### ISSUE TITLE
The string size for the given CHAR/NCHAR data is not defined. Please use an explicit CAST or CONVERT to CHAR(n)/NCHAR(n)

### ISSUE THREAD

**Issue by psrinivasa2** [wiltondb/wiltondb#65] opened 2024-10-03 05:35 UTC
Hi Alex @staticlibs ,
Getting below issue and shared you the log file details in mail, can you please check

The string size for the given CHAR/NCHAR data is not defined. Please use an explicit CAST or CONVERT to CHAR(n)/NCHAR(n)

**Comment by staticlibs** [comment] 2024-10-03 19:49
@psrinivasa2

Thanks for the details! Here is the backtrace from your log:

```
	at babelfishpg_tds!TdsGetGenericTypmod (tdsresponse.c:1495:63) [0x6a1d4772]
	at babelfishpg_tds!PrepareRowDescription (tdsresponse.c:1665:9) [0x6a1d20c3]
	at babelfishpg_tds!TdsSendRowDescription (tdsresponse.c:2589:0) [0x6a1d5985]
	at postgres!standard_ExecutorRun (execMain.c:359:0) [0x401887c7]
	at pg_stat_statements!pgss_ExecutorRun (pg_stat_statements.c:1012:0) [0x01b82391]
	at postgres!PortalRunSelect (pquery.c:926:0) [0x40353c93]
	at postgres!PortalRun (pquery.c:775:0) [0x40352e98]
	at babelfishpg_tsql!execute_plan_and_push_result (pl_exec-2.c:3183:0) [0x61f5f9dc]
	at babelfishpg_tsql!exec_stmt_execsql (pl_exec.c:4849:21) [0x61f5b68d]
	at babelfishpg_tsql!dispatch_stmt (iterative_exec.c:847:0) [0x61f52bb4]
	at babelfishpg_tsql!dispatch_stmt_handle_error (iterative_exec.c:1214:11) [0x61f5386f]
	at babelfishpg_tsql!exec_stmt_iterative (iterative_exec.c:1527:23) [0x61f5d136]
	at babelfishpg_tsql!pltsql_exec_function (pl_exec.c:673:0) [0x61f626f0]
	at babelfishpg_tsql!pltsql_inline_handler (pl_handler.c:4565:0) [0x61f47e56]
	at babelfishpg_tds!SPExecuteSQL (tdsrpc.c:536:0) [0x6a1dd19d]
	at babelfishpg_tds!ProcessTDSRequest (tdsprotocol.c:388:0) [0x6a1cfb1d]
	at babelfishpg_tds!TdsSocketBackend (tdsprotocol.c:644:0) [0x6a1d00fb]
	at babelfishpg_tds!pe_process_command (tds_srv.c:429:5) [0x6a1e3f52]
	at postgres!PostgresMain (postgres.c:4624:0) [0x4034eefc]
	at postgres!SubPostmasterMain (postmaster.c:5185:0) [0x402c0dac]
	at postgres!main (main.c:194:10) [0x401e1f97]
	at postgres!__scrt_common_main_seh (exe_common.inl:288:34) [0x404fb8f4]
	at KERNEL32!BaseThreadInitThunk (unknown_file:0:0) [0xaf13257d]
	at ntdll!RtlUserThreadStart (unknown_file:0:0) [0xb144af28]
```

Though the query that causes it is too big to reproduce this in a minimal example quickly. I would think that the problem is related to `CASE` as there were multiple fixes in that area in the latest Babelfish. I will try to find a reproducible example for this. If you can share the DDL for tables used in the query - that can be helpful.

**Comment by staticlibs** [comment] 2024-10-08 21:35
Minimal reproducers:

```tsql
select 
    case when 1 > 0 then 'foo'
	else cast('bar' as char(3))
end
```

```tsql
select 
    case when 1 < 0 then cast('foo' as char(3))
	else 'bar'
end
```

This problem was fixed in upstream Babelfish just a few days ago - [#2931](https://github.com/babelfish-for-postgresql/babelfish_extensions/pull/2931). I can confirm that the backport is working with WiltonDB and is going to be included into the upcoming release. The update is only blocked now by the completion of #53.

**Comment by psrinivasa2** [comment] 2024-10-14 03:43
Hi Alex,
I was on holiday for last week, couldn't get chance to check it. Thanks for the update,

**Comment by staticlibs** [comment] 2024-10-14 08:04
@psrinivasa2 

Just to confirm, that the installer update with [#2931](https://github.com/babelfish-for-postgresql/babelfish_extensions/pull/2931) included should be available shortly.

**Comment by psrinivasa2** [comment] 2024-10-14 08:55
Hi @staticlibs,
Below is tested from myside added comments, can you check if you miss to get notification
https://github.com/wiltondb/wiltondb/issues/53

**Comment by staticlibs** [comment] 2024-10-14 10:18
@psrinivasa2 

Yes, thanks for heads up, missed that one, commented now.

**Closed** 2024-11-19 03:46 UTC
Labels: bug, fixed
