### ISSUE TITLE
wdb_transfer can't backup data from SQL Server.

### ISSUE THREAD

**Issue by CandyMi** [wiltondb/wiltondb#15] opened 2024-04-12 09:42 UTC
hi @staticlibs !

  When I export the database table of real business from `SQL Server`, it's gave the following error message:

```bash
Running export ...
Export file: D:\bak\local_bcp_20240412.zip
Running bcp ....
Creating bcp format file: zworld.worldSpacesTx
Exporting data: zworld.worldSpacesTx

bcp process failure: stream did not contain valid UTF-8
```

  What adjustments should I make to ensure it continues to work?  :-)

**Comment by staticlibs** [comment] 2024-04-12 13:18
Hi, thanks for the report! If I am reading this correctly, in your case BCP summary output is not in UTF-8 and need to be handled in wdb_transfer more carefully instead of blindly trying to read it as UTF-8. Will try to reproduce and fix this right now.

PS: moved the issue to the main repo.

**Comment by staticlibs** [comment] 2024-04-12 14:52
Should be fixed now, please try [this version](https://github.com/wiltondb/wdb_transfer/releases/tag/1.1.1).

Also, if you see any obvious shortcomings or have some suggestions about the transfer tool - they are very welcome!

**Comment by CandyMi** [comment] 2024-04-15 01:57
```bash
Compressing: mail.notifications.bcp
Creating bcp format file: mail.references
SQLState = 37000, NativeError = 156
Error = [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]�ؼ��� 'references' �������﷨����
SQLState = 37000, NativeError = 11501
Error = [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]���ڱ�������޷���������������
bcp process failure: command ["bcp.exe", "local_data.mail.references", "format", "nul", "-f", "mail.references.xml", "-x", "-n", "-k", "-K", "ReadOnly", "-S", "127.0.0.1,1433", "-U", "sa", "-P", "123456789"] exited with code 1
```

  The garbled code prevents me from getting more useful information.

**Comment by staticlibs** [comment] 2024-04-15 08:39
Can you please try to run the same BCP command manually from the command line to get the full error:

```
bcp.exe local_data.mail.references format nul -f mail.references.xml -x -n -k -K ReadOnly -S 127.0.0.1,1433 -U sa -P 123456789
```

It tries to [create a format file](https://learn.microsoft.com/en-us/sql/relational-databases/import-export/create-a-format-file-sql-server?view=sql-server-ver16&tabs=xml) for table `references` in schema `mail` in db `local_data`. And MSSQL returns some error about the `references` table that is garbled.

**Comment by staticlibs** [comment] 2024-04-15 09:17
Reproduced this locally, `references` table name is a keyword and needs to be enclosed in quotes when invoking BCP. For some reason I cannot pass it successfully in `cmd.exe`, but it works for me from the Transfer app. Will release an app update in a few minutes.

**Comment by CandyMi** [comment] 2024-04-15 09:47
> Can you please try to run the same BCP command manually from the command line to get the full error:
```
bcp.exe local_data.mail.references format nul -f mail.references.xml -x -n -k -K ReadOnly -S 127.0.0.1,1433 -U sa -P 123456789
```

```bash
SQLState = 37000, NativeError = 156
Error = [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]关键字 'references' 附近有语法错误。
SQLState = 37000, NativeError = 11501
Error = [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]由于编译错误无法分析该批处理。
```

@staticlibs

**Comment by staticlibs** [comment] 2024-04-15 09:48
This [updated version](https://github.com/wiltondb/wdb_transfer/releases/tag/1.1.2) should work with `references` table.

**Comment by CandyMi** [comment] 2024-04-15 10:06
hi @staticlibs 

 The export was completed correctly, but an exception occurred before I started importing.:

```bash
Running import: D:\bak\local_data_bcp_20240415.zip ...
Unpacking accounting.automaticBillPayment.bcp into directory D:\bak\local_data_bcp_20240415
Importing file: accounting.automaticBillPayment.bcp
SQLState = 37000, NativeError = 33557097
Error = [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]relation "local_data_accounting.automaticbillpayment" does not exist
bcp process failure: command ["bcp.exe", "[local_data].[accounting].[automaticBillPayment]", "in", "accounting.automaticBillPayment.bcp", "-S", "tcp:127.0.0.1,1433", "-k", "-E", "-m", "1", "-U", "wilton", "-P", "wilton", "-f", "accounting.automaticBillPayment.xml"] exited with code 1

```

**Comment by staticlibs** [comment] 2024-04-15 11:09
> relation "local_data_accounting.automaticbillpayment" does not exist

Based on this message, can you please re-check that DB name is selected correctly on the `Import` tab (it defaults to `master`). And that this DB contains an empty table `automaticbillpayment` in `local_data_accounting` schema. BCP only copies records, unlike `pg_dump` it is not supposed to create tables automatically. DB schema expected to be exported from MSSQL and created in Babelfish manually, see [Schema-import-with-SSMS](https://github.com/wiltondb/wiltondb/wiki/Schema-import-with-SSMS). Also when exporting schema I suggest to only export tables, views, functions and procedures - skipping users, roles and DB itself. If the problem persists when the table is there - more details may be present in server log.

**Comment by CandyMi** [comment] 2024-04-15 12:00
My approach: Create an empty database `local_data`, then select the `backupfile.zip` file and mark all table names and click `Start Import`.

  I want to use `wiltondb transfer` to complete the entire process, because my plan is to import the data backed up from `SQL Server` into `WiltonDB`.

**Comment by CandyMi** [comment] 2024-04-16 03:57
Although I'm a little embarrassed, I really don't know how to operate it.

  I currently only have data backed up from `SQL Server` by `Wilton data transfer tool`. So, I want to try to restore this data from `transfer tool` to `WiltonDB`.

  I don't know much about other `MSSQL` data recovery methods, so if you can help me solve the problem of `transfer tool` recovering data then I can continue to test `WiltonDB`.  :-)

**Comment by staticlibs** [comment] 2024-04-16 15:10
No problem! Unfortunately there is no cohesive description about the data migration, only piecemeal wiki articles. Will try to summarize them here with a simple example:

Connect to MSSQL from SSMS:

```tsql
select @@version

Microsoft SQL Server 2022 (RTM) - 16.0.1000.6 (X64) 
	Oct  8 2022 05:58:25 
	Copyright (C) 2022 Microsoft Corporation
	Express Edition (64-bit) on Windows 10 Home 10.0 <X64> (Build 19045: ) (Hypervisor)
```

Create DB `local_data` and a test table in it:

```tsql
create database local_data
go

use local_data
go

create table tab1(col1 int)
go

insert into tab1 values(42)
go
```

In SSMS Object Explorer right-click `local_data` DB and choose `Tasks -> Generate Scripts`:

![01](https://github.com/wiltondb/wiltondb/assets/9497509/1d7612f6-6d37-496a-8d65-add6053d5da5)

On next screen select "Select specific database objects" and choose only "Tables" (in real DB, also Views, Procedures and UDFs):

![02](https://github.com/wiltondb/wiltondb/assets/9497509/6cf2fef9-1af3-435e-a101-be814de1fa20)

On next screen choose "Output to file":

![05](https://github.com/wiltondb/wiltondb/assets/9497509/daf88b9d-66ff-4c2c-b433-271aaf127209)

Click "Advanced" button on top:

![04](https://github.com/wiltondb/wiltondb/assets/9497509/156aad85-d0a8-458a-9a54-284fdd0006e1)

Make sure "Schema only" is chosen, I also usually uncheck "Script USE DATABASE" to select it manually when the script is run.

Proceed to generate the `local_data.sql` script:

![07](https://github.com/wiltondb/wiltondb/assets/9497509/b84b68cf-adfc-4ec7-ad1c-a544a6bcc6c9)

Now run the Transfer tool and export `tab1` contents from MSSQL:

![08](https://github.com/wiltondb/wiltondb/assets/9497509/86961591-451e-4ce5-bcb3-e3ac3fde684f)
![09](https://github.com/wiltondb/wiltondb/assets/9497509/603b787d-c18d-45f0-bd11-2f88738b3e34)

Connect to WiltonDB in SSMS:

```tsql
select @@version

Babelfish for PostgreSQL with SQL Server Compatibility - 12.0.2000.8
Apr 14 2024 22:44:21
Copyright (c) Amazon Web Services
PostgreSQL 15.4 (Babelfish 3.3.0)
```

Create `test1` DB in WiltonDB:

```tsql
create database test1
go
use test1
go
```

Open `local_data.sql` script in SSMS, making sure that it is open in WiltonDB session and that `test1` DB is selected (re-run `use test1` just in case) and run it to create an empty `tab1` table:

```tsql
/****** Object:  Table [dbo].[tab1]    Script Date: 4/16/2024 3:04:56 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[tab1](
	[col1] [int] NULL
) ON [PRIMARY]
GO
```

In Transfer tool, connect to WiltonDB, make sure that `test1` DB is chosen in dropdown, then run the import:

![10](https://github.com/wiltondb/wiltondb/assets/9497509/61a6f2c4-4ff4-4e01-8911-db68ca3baad7)
![11](https://github.com/wiltondb/wiltondb/assets/9497509/9a1e96f0-0deb-466f-8f64-2e1ed0936889)

Check that data was actually imported:

```tsql
SELECT TOP (1000) [col1]
  FROM [test1].[dbo].[tab1]
```

Hope this helps!

**Comment by CandyMi** [comment] 2024-04-17 03:48
Thank you so much for your patience guidance.

  Following your guidance, I was able to generate the `script.sql` file normally. However, the following error occurred during rebuilding the table:

```bash
Changed database context to 'local_data'.
message 33557097，level 16，state 1，line 9
schema "local_data_accounting" does not exist

完成时间: 2024-04-17T11:14:42.3395624+08:00
```

Here is a partial summary of my execution script:

```sql
create database local_data
go
use local_data
go
/****** Object:  Table [accounting].[automaticBillPayment]    Script Date: 2024/4/17 10:37:31 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [accounting].[automaticBillPayment](
	[ownerID] [int] NOT NULL,
	[billTypeID] [int] NOT NULL,
 CONSTRAINT [automaticBillPayment_PK] PRIMARY KEY CLUSTERED 
(
	[ownerID] ASC,
	[billTypeID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 100, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [FILEGROUP_DEFAULT]
) ON [FILEGROUP_DEFAULT]
GO
...
..
.
```

  Fortunately, I found that this problem was related to `CREATE SCHEMA accounting GO`, which means that I only got the above error when `accounting` did not exist.

  However, the database I use has thousands of `schema` internally. Is there an option to create it automatically?

**Comment by staticlibs** [comment] 2024-04-17 17:54
Schema object type should be checked in this case when generating DDL script from SSMS.

Assuming the following DB in MSSQL:

```tsql
create database test1
go
use test1
go
create schema schema2
go
create table schema1.tab1(col1 int)
insert into schema1.tab1 values(42)
go
create table schema2.tab2(col2 int)
insert into schema2.tab2 values(43)
go
```

Make sure "Schemas" node is checked in Script Generation dialog:

![03](https://github.com/wiltondb/wiltondb/assets/9497509/1e228db4-789b-4aa6-8034-2060eb137227)

Then shemas will be listed in the resulting screen:

![04](https://github.com/wiltondb/wiltondb/assets/9497509/9daa02eb-c97a-4773-92b9-5db14794058c)

And generated script will look like this:

```tsql
USE [test1]
GO
/****** Object:  Schema [schema1]    Script Date: 4/17/2024 6:44:50 PM ******/
CREATE SCHEMA [schema1]
GO
/****** Object:  Schema [schema2]    Script Date: 4/17/2024 6:44:50 PM ******/
CREATE SCHEMA [schema2]
GO
/****** Object:  Table [schema1].[tab1]    Script Date: 4/17/2024 6:44:50 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [schema1].[tab1](
	[col1] [int] NULL
) ON [PRIMARY]
GO
/****** Object:  Table [schema2].[tab2]    Script Date: 4/17/2024 6:44:50 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [schema2].[tab2](
	[col2] [int] NULL
) ON [PRIMARY]
GO
```

Then export data from MSSQL:

![01](https://github.com/wiltondb/wiltondb/assets/9497509/92f0af8f-d271-4e31-b734-507d140b9ec7)
![02](https://github.com/wiltondb/wiltondb/assets/9497509/7eab95f1-0f02-46f8-9060-57d9f778724a)

Create `test1` DB in WiltonDB, run generated DDL script there and import the data into created tables:

![05](https://github.com/wiltondb/wiltondb/assets/9497509/d5bf77f8-1b8f-4fc6-8993-13d69c88aaf0)
![06](https://github.com/wiltondb/wiltondb/assets/9497509/cea95508-c9c7-40b9-9a2d-5ccf3fd17f6d)

**Comment by CandyMi** [comment] 2024-04-18 07:55
Thanks for your guidance, I have successfully rebuilt the database.

  Although there are still some other minor problems in the process, you can modify them according to the prompts and skip them.

**Closed** 2024-04-22 07:25 UTC
Labels: bug
