### ISSUE TITLE
Bug - Wdb_Transfer - If a table column order in Source DB (SQL) is different from destination DB (babelfish), the import fails

### ISSUE THREAD

**Issue by psrinivasa2** [wiltondb/wiltondb#52] opened 2024-09-06 11:05 UTC
Hi Alex @staticlibs,
Noticed a bug in transfer tool today that If a table column order in Source DB (SQL) is different from destination DB (babelfish), the import fails since it is happening based on index and not exact column names.

Below is the sample,
SQL -> Employee(Id, Age, Name, Salary)
Babelfish -> Employee(Id, Name, Salary, Age)

Can the import of the database be based on column's instead of index?

One more thing, what I noticed is if source database has a table and destination table doesn't (for example system table in SQL dbo.mschange_tracking_history), the import fails rather than skipping it.

**Comment by staticlibs** [comment] 2024-09-06 11:50
@psrinivasa2 

In general, `wdb_transfer` requires source and target DB schemas to be completely synchronized. If schemas are different - then manual intervention is required.

> Can the import of the database be based on column's instead of index?

It should be possible to do this manually by [modifying the XML format file](https://learn.microsoft.com/en-us/sql/relational-databases/import-export/use-a-format-file-to-map-table-columns-to-data-file-fields-sql-server?view=sql-server-ver16), but I don't think this is feasible to do automatically.

> One more thing, what I noticed is if source database has a table and destination table doesn't (for example system table in SQL dbo.mschange_tracking_history), the import fails rather than skipping it.

Currently import is assumed to be either successful (all selected tables are imported) or failed (destination DB needs to be dropped and DDL needs to be rerun before repeating the import). Introspecting destination DB and do not allow to choose tables for import that don't exist - this is possible, but it is not really useful - table may exist with different columns. And introspecting destinations tables to check columns and their types against the XML format file - such task is pretty large.

If schemas are not fully synchronized - currently the only option is to exclude the tables that are absent/different by not selecting them in GUI or deleting them from the input ZIP file. And then to deal with such outlier tables manually (for example, running `bcp` directly with a modified format file).

**Comment by psrinivasa2** [comment] 2024-09-06 12:55
We have around 5000 customer's, doing it manually is impossible, any other suggestion to rectify it?

**Comment by psrinivasa2** [comment] 2024-09-06 13:57
In parallel, I am investing from our end what can be done for this, like the reorder exists in both Dev and PRD or only in dev

**Comment by staticlibs** [comment] 2024-09-06 14:07
@psrinivasa2 

The main point is that synchronized schemas is basically a requirement for `wdb_transfer`. If schemas are expected to be different, it may be better to write a custom script/app that will implement all required data migration logic, perhaps doing plain inserts instead of using `bcp`.

**Comment by staticlibs** [comment] 2024-09-08 10:27
@psrinivasa2 

I've added a command-line tool, that can export schema definition for a single table - [wdb_schema](https://github.com/wiltondb/wdb_schema) ([docs](https://github.com/wiltondb/wiltondb/wiki/WiltonDB-Schema-Export-command%E2%80%90line-tool)). It may allow to simplify schema comparison operations from scripting/automated env where schema export with SSMS GUI is inconvenient. Note, this tool may work on WiltonDB in simple cases, but in general only intended to be used with MSSQL. Currently it can export either single table definition, or the whole DB - this can be extended if needed.

If schema synchronization (before data import) is problematic and data import logic must be non-trivial, then there is also an option to register MSSQL instance as a [Linked Server](https://github.com/wiltondb/wiltondb/wiki/Linked-Servers-and-OPENQUERY) in WiltonDB and fetch and transform data using T-SQL code. Importing data from Linked servers (using four-part naming or `OPENQUERY`) is less performant than using `wdb_transfer/bcp` (for example, all remote query records are buffered in memory), but still can be convenient if data set is not too large.

**Comment by psrinivasa2** [comment] 2024-09-09 06:50
Thanks Alex, I will checkit.

With respect to performance of migration in wdb_transfer tool, what are your test results? like a 10GB data transfer, how long it took?

**Comment by staticlibs** [comment] 2024-09-09 07:15
@psrinivasa2 

`wdb_transfer` performance is limited by the number of tables - new connection is opened for every table. There is no workaround to this while `bcp` is used to perform actual data transfer (and there is no plans to use some other way for bulk copy instead of `bcp`). In my experience, with hundreds of tables (when most of the tables have 100 - 1000 rows, and only some of them - millions of rows) the time required to establish the connection to WiltonDB far exceeds the actual data transfer time.

For example, when importing 450 tables, expecting 2 seconds per table, the overall time should be around 15 minutes.

**Comment by psrinivasa2** [comment] 2024-09-09 11:03
We have around 857 tables and maximum size of this could be 10 GB limit, what is your predictions for data transfer performance in linked server?

_Importing data from Linked servers (using four-part naming or OPENQUERY) is less performant than using wdb_transfer/bcp (for example, all remote query records are buffered in memory), but still can be convenient if data set is not too large._


Also, Any idea on what other reliable and available open source tools for data transfer and how AWS team is handling for postgreSQL aurora transfer?

**Comment by staticlibs** [comment] 2024-09-09 11:17
@psrinivasa2 

> what is your predictions for data transfer performance in linked server?

Linked servers do not have the problem with re-opening the connection for every table. Connections to remote MSSQL will be reused properly. Just the `bcp` is well suited for importing multi-GB data into a single table as efficiently as possible - with proper streaming from input file to a DB table and with no data conversion at all. And, to the contrary, with Linked Servers the whole query results are buffered in memory before this data is available to local T-SQL code to perform the insert. So the general advice (from MSSQL world) is to use batch size of 1 - 10 thousand records (committing the transaction after every batch) while copying data with `OPENQUERY`. Also records are converted to-from UTF8-UTF16 multiple times with Linked Servers (unlikely to be a bottleneck).

> Also, Any idea on what other reliable and available open source tools for data transfer and how AWS team is handling for postgreSQL aurora transfer?

I believe on AWS they use [DMS](https://aws.amazon.com/dms/), but I don't have first hand experience with it. Specifically with Babelfish they use `bcp` too (though the problem with slow connection re-opening is much less severe on Linux/Aurora). Some more links on Aurora docs - [one](https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/babelfish-migration.html), [two](https://aws.amazon.com/blogs/database/migrate-your-sql-server-database-to-babelfish-for-aurora-postgresql-using-the-bulk-copy-program-utility/).

**Comment by psrinivasa2** [comment] 2024-09-09 12:14
Alex, How do you see below approach.

1) Take the xml files from correct schema database (may be using wdb_transfer tool back up and remove all the 'bcp.zstd' files and keep only xml files and zip it naming schema_correction zip file)

2) Add this schema_correction zip file as part of deployment package

3) Take the backup from needed SQL database naming as db_backup zip file

4) write a powershell script file that will extract both zip files and copy ONLY the xml files from schema_correction zip to db_backup zip file and zip it back

5) Now the  db_backup file has the correct schema file which can be used to import in babelfish

**Comment by staticlibs** [comment] 2024-09-10 00:01
@psrinivasa2 

I am afraid this will not work, I would assume that XML files in this case must contain actual remapping logic, not just the 1-to-1 description of a "correct" schema.

The task is highly business-specific, so I may not know some crucial details, still I would have used something like the following approach for such task:

1. collect a list of potentially problematic (potentially locally modified) tables
2. run `wdb_transfer.exe` for customer MSSQL DB
3. unpack the generated ZIP and iterate over the exported tables
4. if the table name does not exist in the "correct" schema (list of all tables that exist is known) - run `wdb_schema.exe` on MSSQL for this particular table and run generated table DDL on WiltonDB
5. if the table name is in the "problematic list", then run `wdb_schema.exe` on MSSQL for this table, drop this table in WiltonDB (may need to disable foreign keys), re-create this table in WiltonDB running the DDL for this table generated by `wdb_schema.exe`, enabled back foreign keys
6. at this point customer WiltonDB shema is expected to be completely synchronized with customer MSSQL one, so we can run `wdb_transfer.exe` to import for all exported tables
7. now customer DB in WiltonDB contains the exact copy of customer MSSQL data - so client app should be able to run on it
8. while schema in WiltonDB is slightly different from the correct one, it can be fixed by preparing and running T-SQL snippets for every problematic table, such snippet will create the copy of the table with the correct order of columns, copy the data with `SELECT ... INTO`, drop old table, rename new table

Assuming that the exhaustive list of "problematic" tables can be collected somehow and this list is not too long - then the above approach should be possible to fully automate (by a powershell script) and it should run in a reasonable time.

**Comment by psrinivasa2** [comment] 2024-09-10 05:13
Hi Alex,
I am thinking about one more approach like generate tables schema's dynamically from source SQL database silently and execute it in babelfish, still sp's functions, views other stuff can be fixed. I am searching how table creation steps can be automated

**Comment by psrinivasa2** [comment] 2024-09-10 05:42
we will not be able to identify problematic tables since we have more tables, customer counts also high

**Comment by staticlibs** [comment] 2024-09-10 08:25
> I am searching how table creation steps can be automated

For a single table, something like this should work:

```
wdb_schema.exe -s mssql_host -p mssql_port -u mssql_user -p mssql_password -d db_name -t table_name > tab1.sql 2  > error.log
```
```
sqlcmd -S wdb_host,wdb_port -U wdb_user -P wdb_password -d db_name -i tab1.sql > sqlcmd_log.txt 2>&1
```

[wdb_schema.exe](https://github.com/wiltondb/wiltondb/wiki/WiltonDB-Schema-Export-command%E2%80%90line-tool) currently cannot export multiple tables at once and does not include `DROP` in generated SQL - this can be extended.

> we will not be able to identify problematic tables since we have more tables, customer counts also high

I wonder if it would it be possible for you to run the schema export in automatic/headless way on all deployments? To collect all resulting schema files, and then to run a `diff` between every exported file and the "correct" schema - this way it may be possible to detect all table columns discrepancies (and collect the problematic table names list) without manually going through each deployment.

**Comment by psrinivasa2** [comment] 2024-09-11 12:19
Hi Alex, 
I am trying various approach to solve the column order issue, I will let you know If I arrive a solid solution. could you help us, what could be the reason?

In another context, one of my colleague is facing the error while importing the data,

Running import: C:\CP\Wilton DB\Postgress\SQL DB Backup\employee_bcp_20240911.zip ...
Unpacking emp.table.bcp into directory C:\CP\Wilton DB\Postgress\SQL DB Backup\employee_bcp_20240911
Importing file: emp.table.bcp
bcp process failure: command ["bcp.exe", "[employee].[emp].[table]", "in", "emp.table.bcp", "-f", "emp.table.xml", "-k", "-E", "-m", "1", "-S", "tcp:EHILP-573,2433", "-T"] exited with code 1

_I changed my db, schema and table name above._

2024-09-11 17:40:44.204 IST [10476] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host. 
2024-09-11 17:40:44.204 IST [10476] CONTEXT:  TDS Protocol: Message Type: RPC, SP Type: Unknown (Pre-Parsing Request), Phase: TDS_REQUEST_PHASE_FETCH. Reading data from socket
2024-09-11 17:40:47.809 IST [14588] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host. 
2024-09-11 17:40:47.809 IST [14588] CONTEXT:  TDS Protocol: Message Type: RPC, SP Type: Unknown (Pre-Parsing Request), Phase: TDS_REQUEST_PHASE_FETCH. Reading data from socket
2024-09-11 17:41:20.005 IST [26756] LOG:  could not accept SSL connection: No such file or directory
2024-09-11 17:41:20.005 IST [26756] CONTEXT:  TDS Protocol: Message Type: TDS Pre-Login, Phase: Login. Setup SSL Handshake

**Comment by staticlibs** [comment] 2024-09-11 23:10
@psrinivasa2 

The error happens when Postgres is establishing TLS connection and OpenSSL returns "No such file or directory" from some syscall. I assume OpenSSL cannot load some resource from FS, but I cannot reproduce the error in exact form, errors with missed cert/key files or missed dep libs are different. Can you please share the `bcp` client-side error message, there should be entries like this:

```
SQLState = 37000, NativeError = 33557097
Error = [Microsoft][ODBC Driver 17 for SQL Server][SQL Server] ...
```

before the `bcp process failure` entry.

To troubleshoot the problem I suggest to do the following:

1. check the consistency of WiltonDB installed files - copy `C:\Program Files\WiltonDB Software\wiltondb3.3` directory (excluding `data`), then run `Repair` on WiltonDB installation, then compare the original and copied directories with `KDiff3` or some other dir diff tool:

![17](https://github.com/user-attachments/assets/1704406e-5e63-47e8-a93f-218079ae79c6)

2. Look at the TLS handshake in WireShark - to find out whether client (`bcp`) or server actually fails first and sends TCP `RST` message to abort the connection.

3. Assuming installation is consistent and the failure happens on server - trace the OpenSSL syscalls done from `postgres.exe` process using [ProcMon](https://learn.microsoft.com/en-us/sysinternals/downloads/procmon) utility, to find out which FS path access attempt returns the "No such file or directory" from OS to OpenSSL.

**Comment by psrinivasa2** [comment] 2024-09-13 09:05
@staticlibs , We are not seeing kind of below entry anywhere, can you please be specific on where exactly this needs to be checked? And also we have done uninstallation of wiltonDB and delete program files/wiltonDB software, tried again, still same issue. The rest of 2 points we yet to try out

SQLState = 37000, NativeError = 33557097
Error = [Microsoft][ODBC Driver 17 for SQL Server][SQL Server] ...

**Comment by staticlibs** [comment] 2024-09-13 09:17
@psrinivasa2 

I meant the output that is coming from `bcp.exe` itself. Please use `bcp.exe` directly for all troubleshooting (copying the command from `wdb_transfer` to console). I also suggest to check that `bcp.exe` and its dependencies (ODBC 17) are installed correctly - to check it first on simple examples with both MSSQL and WiltonDB.

**Comment by psrinivasa2** [comment] 2024-09-13 09:24
okay got it

**Comment by psrinivasa2** [comment] 2024-09-13 09:41
To get this quickly, can you share me sample bcp command for a table, below the export details we have for a table

![image](https://github.com/user-attachments/assets/962575d1-222d-4b6a-8f99-015cf059045a)

**Comment by staticlibs** [comment] 2024-09-13 09:55
@psrinivasa2 

The command is:

```
bcp.exe [mydb].[AccessControl].[Activity] in AccessControl.Activity.bcp -f AccessControl.Activity.xml -k -E -m 1 -S tcp:EHILP-573,2433 -T 
```

Just you needs to decompress the `AccessControl.Activity.bcp.zstd` file first using [Zstandard command line decompressor](https://github.com/facebook/zstd/releases).

**Comment by psrinivasa2** [comment] 2024-09-13 12:31
![image](https://github.com/user-attachments/assets/c36a2e47-7d3c-4eae-afb5-8e9dab012ff4)

Nothing happens in my colleague machine, but the same start's copying for my machine

**Comment by psrinivasa2** [comment] 2024-09-13 12:45
![image](https://github.com/user-attachments/assets/df80d2c1-d59a-42fa-9b74-56cc0a4bac1e)

ODBC 17 exists on her machine

![image](https://github.com/user-attachments/assets/23e98154-5840-4f98-b10f-4d9831f39ed5)

Nothing happens when she execute the command

**Comment by staticlibs** [comment] 2024-09-13 14:13
@psrinivasa2 

Thanks for the details, so the behaviour is the same with both `wdb_transfer` and the direct `bcp` call.

I wonder if you can check the same `bcp` command with MSSQL and also to check the same `bcp` command to the same instance of WiltonDB running it from another machine? The idea is to verify whether the connection problem happens on client or on server.

**Comment by psrinivasa2** [comment] 2024-09-13 14:59
also to check the same bcp command to the same instance of WiltonDB running it from another machine? 
 
I will check on MSSQL, the above point in couldn't get

**Comment by psrinivasa2** [comment] 2024-09-16 10:59
![image](https://github.com/user-attachments/assets/83fddb44-4e55-4f18-b935-0fa666a29f7d)

MSSQL works fine with BCP , Alex @staticlibs

**Comment by staticlibs** [comment] 2024-09-16 11:22
@psrinivasa2 

Thanks for the details! Running this `bcp` example with MSSQL - can you please also check that it actually uses TLS? In ODBC 17 (that is used by `bcp`) TLS encryption is off by default. I assume it should be on automatically when Windows Auth is used - by it is better to check.

Running `bcp` with WiltonDB:

1. can you please check the TLS connection running different instance of `bcp` from other machine over the network (to rule out local problems with `bcp` installation)

2. can you try to disable TLS support in WiltonDB (`ssl=off` parameter in `wdb_config`) and then run the same `bcp` command (connecting with username/password if windows auth fails) to check whether this instance of WiltonDB accepts connections correctly without TLS:

![18](https://github.com/user-attachments/assets/79c76ce7-a51c-4a52-988e-702eb843d6ee)

**Comment by psrinivasa2** [comment] 2024-09-16 12:26
![image](https://github.com/user-attachments/assets/08ff9747-a32b-47ed-ac80-56d5cb96965f)

BCP working after SSL off

**Comment by staticlibs** [comment] 2024-09-16 12:46
@psrinivasa2

Then lets enable the TLS back in WiltonDB and record the TLS handshake with WireShark. It should be at least clear from the recording on which side (client or server) the handshake error happens. And do this recording (with TLS-enabled) twice - with and without Windows Auth.

**Comment by karthika-thirumoorthy** [comment] 2024-09-18 05:42
Alex,

I have attached the trace by,
Running the BCP command (Windows auth, TLS off)
Running the same command with password auth (and TLS still off)
And with TLS on only initial PRELOGIN TDS packets will be captured

Please have a look in it.

Thanks,
Karthika
________________________________

**Comment by staticlibs** [comment] 2024-09-18 06:58
@karthika-thirumoorthy 

> Alex, I have attached the trace by,

It seems that, when GitHub-issues are replied by email - then email attachments are stripped by GitHub. If convenient, please re-send it directly to email.

**Comment by staticlibs** [comment] 2024-09-18 21:08
@karthika-thirumoorthy 

In `TLSONWithWindowAuth.pcapng` you are running WiltonDB with:

```
ssl = on
babelfishpg_tds.tds_ssl_encrypt = off
```

In this mode BCP client gets the following response from the WiltonDB and immediately closes the connection (on client side):

```
Option: Encryption
    Option Token: Encryption (1)
    Option offset: 42
    Option length: 1
    Encryption: Encryption is available but off (0)

```

It is not clear why this behaviour of `bcp` occurs, and I cannot see anything wrong with WiltonDB pre-login response. I would guess that some kind of TLS enforcement is enabled on this machine for SQL Server client tools (though I don't know the mechanism for such enforcement).

Please try to run WiltonDB with both following options enabled (only in this case `bcp` actually enables TLS - see details in [this comment above](https://github.com/wiltondb/wiltondb/issues/52#issuecomment-2355256201)):

```
ssl = on
babelfishpg_tds.tds_ssl_encrypt = on
```

**Comment by karthika-thirumoorthy** [comment] 2024-10-03 05:00
Hi Alex,

When I try to run BCP command with both following options enabled,

ssl = on
babelfishpg_tds.tds_ssl_encrypt = on

with windows Authentication, Nothing happens when executes the command,
![image](https://github.com/user-attachments/assets/3cd7370b-f4b5-4d6f-8258-4e3a96e88cd6)

without windows Authentication, It copied the rows successfully
![image](https://github.com/user-attachments/assets/a69a7c38-13a4-4950-9a66-a4f084644bd6)

I have sent the trace in a mail. Please have a look.

**Comment by staticlibs** [comment] 2024-10-03 19:23
@karthika-thirumoorthy 

Thanks for the traces! In the `SSLonTLSONWithWindowsAuth.pcapng` trace the `bcp` closes the connection after receiving the server response to `PRELOGIN`. I can guess that `bcp` fails to initiate Windows Auth for some reason, perhaps due to some OS-level security settings. Does the problem happens on a particular machine or in a particular sub-network.

To investigate this I would suggest to use [ProcMon](https://learn.microsoft.com/en-us/sysinternals/downloads/procmon) on `bcp` to find out which syscall is failing for it when Windows Auth is initiated.

Also, if you can record and share the same `bcp` invocation (from the same machine) with MSSQL - this may be helpful, it seems that MSSQL responds somehow differently to `PRELOGIN` and does not cause `bcp` to fail doing Windows auth.

**Comment by karthika-thirumoorthy** [comment] 2024-10-07 07:23
@staticlibs ,

I have attached ProcMon log file with below filters applied,
![image](https://github.com/user-attachments/assets/78467c74-4de3-498a-b3b8-2d84189c66bd)

we are not able to find the actual cause for the issue. 
Please have a look into it. if you find anything different please let us know.
[Logfile.zip](https://github.com/user-attachments/files/17274710/Logfile.zip)


> Also, if you can record and share the same `bcp` invocation (from the same machine) with MSSQL - this may be helpful, it seems that MSSQL responds somehow differently to `PRELOGIN` and does not cause `bcp` to fail doing Windows auth.

When I try to run bcp command and trace in wireShare with tds filter , it doesn't return anything

![image](https://github.com/user-attachments/assets/23f371a8-7e14-4e2f-a0e6-06bb958312bc)

Do we need to apply any other filter in wireShare for MSSQL?

**Comment by staticlibs** [comment] 2024-10-07 08:42
@karthika-thirumoorthy 

> we are not able to find the actual cause for the issue.

Yes, there seems to be no SSPI calls captured, perhaps they happen from some other DLL.

> > Also, if you can record and share the same `bcp` invocation (from the same machine) with MSSQL - this may be helpful, it seems that MSSQL responds somehow differently to `PRELOGIN` and does not cause `bcp` to fail doing Windows auth.
> 
> When I try to run bcp command and trace in wireShare with tds filter , it doesn't return anything

Thanks for these details! So MSSQL does not use plain `PRELOGIN` packet at all, it uses some newer TDS capabilities to establish the TLS connection. Thus the details are not seen in WireShark.

Overall, given the collected evidence, I would attribute the problem to some OS-level (or ODBC-level) security settings that require `bcp` to use "more secure" login with Windows Auth and this login is not supported in Babelfish (so the SSPI logic implemented in WiltonDB is not reached at all - `bcp` closes the connection earlier).

**Comment by karthika-thirumoorthy** [comment] 2024-10-14 04:49
Hi @staticlibs 


> Overall, given the collected evidence, I would attribute the problem to some OS-level (or ODBC-level) security settings that require `bcp` to use "more secure" login with Windows Auth and this login is not supported in Babelfish (so the SSPI logic implemented in WiltonDB is not reached at all - `bcp` closes the connection earlier).

How to check the  OS-level (or ODBC-level) security settings in our machine? Could you please guide us to modify it.

**Comment by staticlibs** [comment] 2024-10-14 10:26
@karthika-thirumoorthy 

[MSSQL security setup](https://learn.microsoft.com/en-us/sql/relational-databases/security/securing-sql-server?view=sql-server-ver16) is a vast topic, and without having a reproducible scenario I don't know where to look to confirm that it is actually a root cause. I've filed #72 to track this (as it is not related to the original problem in this issue), going to look at it after the urgent issues are cleared.

**Comment by psrinivasa2** [comment] 2024-10-14 10:32
Moreover, **Without** windows authentication working even after disabling SSL in configuration as stated above

**Comment by psrinivasa2** [comment] 2024-11-07 07:42
Hi @staticlibs ,
I have solved the column order issues between SQL and Babelfish by writing a powershell script file. Below the script, Can you please review it?


`# Prompt user for SQL Server and Database names
$sqlServer = Read-Host "Enter the SQL Server name (e.g., localhost)"
$database = Read-Host "Enter the Database name (e.g., Employee)"

# Define the SQL query
$query = @"
-- Step 1: Create a temporary table to store the generated SQL scripts
CREATE TABLE #TableScripts (Script NVARCHAR(MAX));
 
-- Step 2: Generate and insert SQL scripts into the temporary table
DECLARE @TableName NVARCHAR(500) = NULL; -- Set this to the specific table name or leave NULL for all tables
DECLARE @SchemaName NVARCHAR(500) = NULL; -- Set this to the specific schema name or leave NULL for all schemas
 
DECLARE @SQL NVARCHAR(MAX) = '';
 
;WITH TableDetails AS (
    SELECT
t.name AS TableName,
        SCHEMA_NAME(t.schema_id) AS SchemaName,
c.name AS ColumnName,
        TYPE_NAME(c.user_type_id) AS DataType,
        c.max_length AS MaxLength,
        c.precision AS Precision,
        c.scale AS Scale,
        c.is_nullable AS IsNullable,
        c.is_identity AS IsIdentity
    FROM sys.columns c
    INNER JOIN sys.tables t ON c.object_id = t.object_id
WHERE (@TableName IS NULL OR t.name = @TableName)
    AND (@SchemaName IS NULL OR SCHEMA_NAME(t.schema_id) = @SchemaName)
), PrimaryKeys AS (
    SELECT
        k.parent_object_id AS object_id,
k.name AS ConstraintName,
c.name AS ColumnName
    FROM sys.key_constraints k
    INNER JOIN sys.index_columns ic ON k.parent_object_id = ic.object_id AND k.unique_index_id = ic.index_id
    INNER JOIN sys.columns c ON ic.object_id = c.object_id AND ic.column_id = c.column_id
    WHERE k.type = 'PK'
)
INSERT INTO #TableScripts (Script)
SELECT
    'CREATE TABLE [' + td.SchemaName + '].[' + td.TableName + '] (' +
    STUFF(
        (
            SELECT
                ', ' + CHAR(13) +
                CHAR(9) + '[' + ColumnName + '] ' + UPPER(DataType) +
                CASE
                    WHEN DataType IN ('varchar', 'char', 'nvarchar', 'nchar')
                        THEN '(' + CASE WHEN MaxLength = -1 THEN 'MAX' ELSE CAST(MaxLength AS VARCHAR(10)) END + ')'
                    WHEN DataType IN ('decimal', 'numeric')
                        THEN '(' + CAST(Precision AS VARCHAR(10)) + ',' + CAST(Scale AS VARCHAR(10)) + ')'
                    ELSE ''
                END +
                CASE
                    WHEN IsNullable = 0 THEN ' NOT NULL' ELSE ' NULL'
                END +
                CASE
                    WHEN IsIdentity = 1 THEN ' IDENTITY(1,1)' ELSE ''
                END
            FROM TableDetails
            WHERE TableName = td.TableName
              AND SchemaName = td.SchemaName
            FOR XML PATH(''), TYPE
        ).value('.', 'NVARCHAR(MAX)'), 1, 2, ''
    ) + CHAR(13) + ');' + CHAR(13) + CHAR(13)
FROM
    (SELECT DISTINCT SchemaName, TableName FROM TableDetails) AS td;
 
-- Step 3: Retrieve and process the SQL scripts from the temporary table
SELECT Script FROM #TableScripts;
 
-- Step 4: Clean up
DROP TABLE #TableScripts;
"@
 
# Define the connection string
$connectionString = "Server=$sqlServer;Database=$database;Integrated Security=True;"

$results = Invoke-Sqlcmd -ConnectionString $connectionString -Query $query -MaxCharLength 10000

if ($results) {
    # capture the sql scripts into a variable	
    $actualsqldbtabledefinition = $results | foreach-object { $_.script } | out-string	
	
} else {
    Write-Host "No results returned from actualSQLDBTableDefinition SQL query."
}

$babelfishBasePSCSchemas = Get-Content -Path "psc-dev.sql" -Raw

# Define a regex pattern to extract the CREATE TABLE statement and column definitions
$regexCreateTable = "CREATE\s+TABLE\s+\[(?<SchemaName>\w+)\]\.\[(?<TableName>\w+)\]\s*\(\s*(?<Columns>[\s\S]+?)\)\s*;"

# Extract the CREATE TABLE statement from actualSQLDBTableDefinition
$actualSQLDBTableDefinitionMatches = [regex]::Matches($actualSQLDBTableDefinition, $regexCreateTable, [System.Text.RegularExpressions.RegexOptions]::Singleline)

if ($actualSQLDBTableDefinitionMatches.Count -gt 0) {
	
	foreach ($actualSQLDBTableDefinitionMatch in $actualSQLDBTableDefinitionMatches) {
		
    # Extract the columns part from actualSQLDBTableDefinition
    $newColumns = $actualSQLDBTableDefinitionMatch.Groups["Columns"].Value.Trim()	
	
	# Extract the table name from actualSQLDBTableDefinition (just for reference)
    $schemaName = $actualSQLDBTableDefinitionMatch.Groups["SchemaName"].Value
    $tableName = $actualSQLDBTableDefinitionMatch.Groups["TableName"].Value
		
	$regexToMatchbabelfishBasePSCSchemas = "CREATE\s+TABLE\s+\[SchemaName\]\.\[TableName\]\s*\((?<Columns>[\s\S]+?)\s*CONSTRAINT"
		
	# Replace 'SchemaName' and 'TableName' with the actual values
	$regexToMatchbabelfishBasePSCSchemas = $regexToMatchbabelfishBasePSCSchemas -replace 'SchemaName', [regex]::Escape($schemaName)
	$regexToMatchbabelfishBasePSCSchemas = $regexToMatchbabelfishBasePSCSchemas -replace 'TableName', [regex]::Escape($tableName)	
	 
    # Now find the corresponding CREATE TABLE statement in babelfishBasePSCSchemas
    $babelfishBasePSCSchemasMatchs = [regex]::Matches($babelfishBasePSCSchemas, $regexToMatchbabelfishBasePSCSchemas, [System.Text.RegularExpressions.RegexOptions]::Singleline)
	
	foreach ($babelfishBasePSCSchemasMatch in $babelfishBasePSCSchemasMatchs) {				
		$existingColumns = $babelfishBasePSCSchemasMatch.Groups["Columns"].Value	 
		
		# Extracting the column names from both lists
		$newcolumnnames = [regex]::matches($newcolumns, '\[(\w+)\]', 'IgnoreCase').foreach({ $_.groups[1].value })
		$existingcolumnnames = [regex]::matches($existingcolumns, '\s\s\[(\w+)\]', 'IgnoreCase').foreach({ $_.groups[1].value })		 
 
		# checking if both arrays have the same count and elements in the same order
		if (($newcolumnnames.Trim() -join ',') -ne ($existingcolumnnames.Trim() -join ',')) {			
			
			 # Initialize an array to store the reordered columns
			$reorderedColumns = @()
			
			# Reorder the existing columns based on the order of new column names
			foreach ($newcolumn in $newcolumnnames) {
				# Find the full column definition from the existing columns for this new column name
				$fullColumnDefinition = [regex]::match($existingColumns, "\[$newcolumn\]\s+\[[^\]]+\][^\[]*").Value				
				if ($fullColumnDefinition) {					
					$reorderedColumns += "$fullColumnDefinition"
				}
			}			
			
			# Replace the columns part in babelfishBasePSCSchemas with the columns from actualSQLDBTableDefinition			
			$babelfishBasePSCSchemas = $babelfishBasePSCSchemas -replace [regex]::Escape($existingColumns.Trim()), $reorderedColumns
			write-host "Order mismatch schama '$schemaName' and table '$tableName' is corrected"
		}		
        break
	   }
	}
}
 
# Save the modified content back to babelfishBasePSCSchemaFile
Set-Content -Path "employee.sql" -Value $babelfishBasePSCSchemas

write-host "Column order correction process between machine SQL and postgreSQL schema is done succesfully!"`

**Comment by staticlibs** [comment] 2024-11-07 13:50
@psrinivasa2 

I think this approach can work.

Just the point on introspection - any specific reason to generate the DDL manually instead of using `wdb_schema.exe`? Manual generation is fine when the possible column types/options are limited, just there are a number of corner cases which are already handled in the [SMO](https://learn.microsoft.com/en-us/sql/relational-databases/server-management-objects-smo/sql-server-management-objects-smo-programming-guide?view=sql-server-ver16) library that `wdb_schema` uses. You actually also can use the SMO API directly from PowerShell, but the installation of these libraries the way they can be used in PowerShell is non-trivial.

Another point is about the parsing of a DDL script with regexes. Again, this should work fine on the restricted number of DDL scripts with known features. Just it may be better to actually run both DDLs (correct and possibly incorrect) for the given table with temporary table names. And then use the catalogs to compare the tables from T-SQL.

**Comment by psrinivasa2** [comment] 2024-11-11 10:33
Hi @staticlibs,
I am taking all tables column definition, the manual query written is bit fast than wdb_schema. Moreover, I am using the SQL DB query output only for comparison and ONLY REORDER babelfish scheme instead of replace of SQL query output

**Closed** 2024-11-19 03:50 UTC
Labels: enhancement, wdb_transfer
