### ISSUE TITLE
Not able to create view after dropping multiple times and try to create new view

### ISSUE THREAD

**Issue by JayakumarEMIS** [wiltondb/wiltondb#80] opened 2024-10-24 12:27 UTC
Hi @staticlibs, I am getting below issue when I am trying to view custom schema, I was testing my application during that multiple times i drop and create again, but when i create again i am getting below, showing some constraint and I ensure that there is no view under the name, but still not able to create, seems some information of view in some table not get clear can you please check and help me to fix, i am sharing sample query and my log as well

```
IF NOT EXISTS (SELECT  schema_name FROM    information_schema.schemata WHERE   schema_name = 'RWR' ) 
BEGIN
EXEC sp_executesql N'CREATE SCHEMA RWR'
END
GO

IF  EXISTS (SELECT * FROM sys.views WHERE object_id = OBJECT_ID(N'[RWR].[DMRView]'))
DROP VIEW [RWR].[DMRView]
GO

CREATE VIEW [RWR].[DMRView]
AS
SELECT  1
GO
```

Log:
```
2024-10-24 17:37:14.230 IST [30148] ERROR:  duplicate key value violates unique constraint "babelfish_view_def_pkey"
2024-10-24 17:37:14.230 IST [30148] DETAIL:  Key (dbid, schema_name, object_name)=(58, RWR, dmrview) already exists.
2024-10-24 17:37:14.230 IST [30148] CONTEXT:  SQL statement "CREATE VIEW [RWR].[DMRView]

	AS

	SELECT  1"
	PL/tsql function inline_code_block line 1 at SQL statement
	TDS Protocol: Message Type: SQL BATCH, Phase: TDS_REQUEST_PHASE_PROCESS. Processing SQL Batch Request
2024-10-24 17:37:14.230 IST [30148] LOG:  sql_batch statement: CREATE VIEW [RWR].[DMRView]

	AS

	SELECT  1

```

**Comment by JayakumarEMIS** [comment] 2024-10-24 12:37
seems the issue when I drop schema, this below sys.babelfish_view_def table not cleared in postgre, eventhough it is dropped in t-sql

![image](https://github.com/user-attachments/assets/5d9b4f3e-d33e-4a30-a973-a6c6e909b4be)

![image](https://github.com/user-attachments/assets/60187dab-7579-4b74-9ece-0c6fe30e3c41)

**Comment by staticlibs** [comment] 2024-10-24 14:29
@JayakumarEMIS 

Thanks for the report! Do you have a scenario how these stray records in `sys.babelfish_view_def` catalog can be produced?

The `DROP SCHEMA` example is incorrect, because "The schema that is being dropped must not contain any objects. If the schema contains objects, the DROP statement fails." ([reference](https://learn.microsoft.com/en-us/sql/t-sql/statements/drop-schema-transact-sql?view=sql-server-ver16)).

**Comment by JayakumarEMIS** [comment] 2024-10-25 06:14
Yes, I dropped the view using below query before drop the view because of dependency, after that only drop the schema, even if dropping the schema in this table not cleared "sys.babelfish_view_def", currently I don't have exact scenario sometimes only it occur, for workaround delete the record manually from that table and working on it, will check when it cause the issue

**Comment by JayakumarEMIS** [comment] 2024-10-25 07:16
Hi @staticlibs, got the scenario but not sure, the issue i think while we creating view in dynamic sql, try the below script and run more than one time, when you run the second time the issue occur please check 

```
IF NOT EXISTS (SELECT  schema_name FROM    information_schema.schemata WHERE   schema_name = 'Mock' ) 
BEGIN
EXEC sp_executesql N'CREATE SCHEMA Mock'
END
GO

IF  EXISTS (SELECT * FROM sys.views WHERE object_id = OBJECT_ID(N'[Mock].[DMRView]'))
DROP VIEW [Mock].[DMRView]
GO


IF NOT EXISTS (SELECT * FROM sys.views WHERE object_id = OBJECT_ID(N'[Mock].[DMRView]'))
EXEC sp_executesql @statement =N'CREATE VIEW [Mock].[DMRView]
AS
SELECT  1'
GO

SELECT * FROM [Mock].[DMRView]

```

**Comment by staticlibs** [comment] 2024-10-25 08:43
@JayakumarEMIS 

Thanks for the example! Just I cannot reproduce it on latest RC (11.16.0.rc6, from this Monday). I can see that the schema is mixed-case, are you sure that this is not the problem from #57? Can you reproduce it with dynamic SQL and lower-case schema name?

**Comment by JayakumarEMIS** [comment] 2024-10-25 09:20
Hi @staticlibs, I am not test on latest RC (11.16.0.rc6, from this Monday), I checked with srini internally he mentioned seems it was fixed in latest release, I will check and update on that thanks

**Comment by staticlibs** [comment] 2024-10-29 11:41
Closing as a duplicate.

**Closed by staticlibs** 2024-10-29 11:41 UTC
Labels: bug
